# Generated by Django 3.0.3 on 2020-04-21 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_newpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
